"""Validated, idempotent storage for images generated by the active Codex session."""

from __future__ import annotations

import base64
import binascii
import hashlib
import io
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from PIL import Image, UnidentifiedImageError

from pixelle_video.utils.os_util import get_data_path

ALLOWED_IMAGE_FORMATS = {
    "PNG": (".png", "image/png"),
    "JPEG": (".jpg", "image/jpeg"),
    "WEBP": (".webp", "image/webp"),
}
_DATA_URL_RE = re.compile(
    r"^data:(?P<mime>image/(?:png|jpeg|jpg|webp));base64,(?P<data>.+)$",
    re.IGNORECASE | re.DOTALL,
)


class AgentImageError(ValueError):
    pass


def save_agent_image(
    *,
    experiment_id: str,
    scene_id: str,
    prompt: str,
    source: dict[str, Any],
    image_data_url: str | None = None,
    file_path: str | None = None,
    replace: bool = False,
    max_size: int = 100 * 1024 * 1024,
    storage_root: Path | None = None,
) -> dict[str, Any]:
    """Persist one Codex image and its provenance sidecar."""

    if bool(image_data_url) == bool(file_path):
        raise AgentImageError("Provide exactly one of image_data_url or file_path")
    if not prompt or not prompt.strip():
        raise AgentImageError("Image prompt is required")

    safe_experiment_id = _safe_component(experiment_id, "experiment_id")
    safe_scene_id = _safe_component(scene_id, "scene_id")
    content = _read_image_bytes(
        image_data_url=image_data_url,
        file_path=file_path,
        max_size=max_size,
    )
    image_format, width, height = _inspect_image(content)
    suffix, media_type = ALLOWED_IMAGE_FORMATS[image_format]
    sha256 = hashlib.sha256(content).hexdigest()

    root = storage_root or Path(get_data_path("uploads", "generation-assets"))
    destination_dir = Path(root) / safe_experiment_id
    destination_dir.mkdir(parents=True, exist_ok=True)
    destination = destination_dir / f"{safe_scene_id}{suffix}"
    sidecar = destination_dir / f"{safe_scene_id}.json"

    existing = _find_existing_scene_image(destination_dir, safe_scene_id)
    if existing is not None:
        existing_sha256 = hashlib.sha256(existing.read_bytes()).hexdigest()
        if existing_sha256 == sha256:
            return _result(
                path=existing,
                scene_id=scene_id,
                sha256=sha256,
                image_format=image_format,
                media_type=media_type,
                width=width,
                height=height,
                size=len(content),
                replaced=False,
                idempotent=True,
            )
        if not replace:
            raise AgentImageError(
                f"Scene {scene_id!r} already has a different image; use replace=true to replace it"
            )

    _atomic_write(destination, content)
    if existing is not None and existing != destination:
        existing.unlink(missing_ok=True)

    metadata = {
        "experiment_id": experiment_id,
        "scene_id": scene_id,
        "prompt": prompt.strip(),
        "source": source,
        "path": str(destination.resolve()),
        "sha256": sha256,
        "format": image_format,
        "media_type": media_type,
        "width": width,
        "height": height,
        "size": len(content),
    }
    _atomic_write(
        sidecar,
        json.dumps(metadata, ensure_ascii=False, indent=2, sort_keys=True).encode("utf-8"),
    )
    return _result(
        path=destination,
        scene_id=scene_id,
        sha256=sha256,
        image_format=image_format,
        media_type=media_type,
        width=width,
        height=height,
        size=len(content),
        replaced=existing is not None,
        idempotent=False,
    )


def _read_image_bytes(
    *,
    image_data_url: str | None,
    file_path: str | None,
    max_size: int,
) -> bytes:
    if image_data_url:
        match = _DATA_URL_RE.match(image_data_url.strip())
        if not match:
            raise AgentImageError("image_data_url must be a base64 PNG, JPEG, or WebP data URL")
        encoded = match.group("data")
        if len(encoded) > ((max_size + 2) // 3) * 4 + 4:
            raise AgentImageError(f"Image exceeds the configured upload limit of {max_size} bytes")
        try:
            content = base64.b64decode(encoded, validate=True)
        except (binascii.Error, ValueError) as exc:
            raise AgentImageError("image_data_url contains invalid base64 data") from exc
    else:
        source_path = Path(file_path or "").expanduser()
        if not source_path.is_file():
            raise AgentImageError(f"Image file does not exist: {file_path}")
        if source_path.stat().st_size > max_size:
            raise AgentImageError(f"Image exceeds the configured upload limit of {max_size} bytes")
        content = source_path.read_bytes()

    if not content:
        raise AgentImageError("Image is empty")
    if len(content) > max_size:
        raise AgentImageError(f"Image exceeds the configured upload limit of {max_size} bytes")
    return content


def _inspect_image(content: bytes) -> tuple[str, int, int]:
    try:
        with Image.open(io.BytesIO(content)) as image:
            image_format = (image.format or "").upper()
            width, height = image.size
            image.verify()
    except (UnidentifiedImageError, OSError, SyntaxError) as exc:
        raise AgentImageError("Image bytes are not a valid PNG, JPEG, or WebP image") from exc

    if image_format not in ALLOWED_IMAGE_FORMATS:
        raise AgentImageError("Only PNG, JPEG, and WebP images are supported")
    if width <= 0 or height <= 0:
        raise AgentImageError("Image dimensions must be positive")
    return image_format, width, height


def _find_existing_scene_image(directory: Path, safe_scene_id: str) -> Path | None:
    for suffix in (".png", ".jpg", ".webp"):
        candidate = directory / f"{safe_scene_id}{suffix}"
        if candidate.is_file():
            return candidate
    return None


def _safe_component(value: str, field_name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise AgentImageError(f"{field_name} is required")
    stripped = value.strip()
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", stripped).strip("._-")
    if not safe:
        safe = hashlib.sha256(stripped.encode("utf-8")).hexdigest()[:16]
    elif safe != stripped:
        digest = hashlib.sha256(stripped.encode("utf-8")).hexdigest()[:10]
        safe = f"{safe[:100]}-{digest}"
    return safe[:120]


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as temp_file:
            temp_file.write(content)
            temp_file.flush()
            os.fsync(temp_file.fileno())
        os.replace(temp_name, path)
    except Exception:
        Path(temp_name).unlink(missing_ok=True)
        raise


def _result(
    *,
    path: Path,
    scene_id: str,
    sha256: str,
    image_format: str,
    media_type: str,
    width: int,
    height: int,
    size: int,
    replaced: bool,
    idempotent: bool,
) -> dict[str, Any]:
    return {
        "scene_id": scene_id,
        "path": str(path.resolve()),
        "sha256": sha256,
        "format": image_format,
        "media_type": media_type,
        "width": width,
        "height": height,
        "size": size,
        "replaced": replaced,
        "idempotent": idempotent,
    }
